 name: Python autotests

 on: [push]

 jobs:
   run-tests:
     runs-on: ubuntu-latest
     name: Run autotests
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
       - name: Set up python environment
         uses: actions/setup-python@v5
         with:
           python-version: '3.13'
       - name: Install dependencies
         run: pip install -r requirements.txt
       - name: Run tests
         run: pytest
